### ISSUE TITLE
Parser is not ignoring \"

### ISSUE THREAD

**Issue by Shackmeister** [KiCad/kicad-library-utils#244] opened 2018-06-24 19:38 UTC
When having a qoutation inside the description, a backslash is added in front to make the parser ignore the qoutation mark. The Parser for the footprints here on Github is not ignoring it, and is causing Travis to not be able to parse the footprints.
https://github.com/KiCad/kicad-footprints/pull/388

**Comment by Ratfink** [comment] 2018-06-24 19:48
Duplicate of #224, with corresponding open PR #225.

**Closed by Ratfink** 2018-06-24 19:48 UTC
